version: '3'
services:
  python:
    image: image_app
    ports:
      - '8080:80'
    networks:
      - monreseau

  mariadb:
    image: image_database
    ports:
      - '7080:80'
    networks:
      - monreseau
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: parc_informatique
      MYSQL_USER: root
      MYSQL_PASSWORD: ''

networks:
  monreseau:
