version: '3'
services:

  python:
    image: image_python
    ports:
      - '8080:80'
    networks: monreseau
    depends_on:
      - image_mariadb

  mariadb:
    image: image_mariadb
    ports:
      - '7080:7080'
    networks: monreseau
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: parc_informatique
      MYSQL_USER: root
      MYSQL_PASSWORD: ''

networks:
  monreseau: